version: '3'

services:

  nginx:
    restart: always
    image: ${DOCKER_REPO}/faceanalysis_nginx:${BUILD_TAG}
    build: ./nginx
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    ports:
      - "${APP_PORT}:80"

  worker:
    restart: on-failure
    image: ${DOCKER_REPO}/faceanalysis_app:${BUILD_TAG}
    build:
      context: ./app
      args:
        DEVTOOLS: ${DEVTOOLS}
    command: ["python3", "worker.py"]
    depends_on:
      - mysql
      - rabbitmq
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${DATA_DIR}:/app/faceanalysis/images"
    environment:
      HOST_DATA_DIR: "${DATA_DIR}"
      MOUNTED_DATA_DIR: /app/faceanalysis/images
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      ALLOWED_IMAGE_FILE_EXTENSIONS: ${ALLOWED_IMAGE_FILE_EXTENSIONS}
      IMAGE_PROCESSOR_QUEUE: ${IMAGE_PROCESSOR_QUEUE}
      DOCKER_DAEMON: ${DOCKER_DAEMON}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DISTANCE_SCORE_THRESHOLD: ${DISTANCE_SCORE_THRESHOLD}
      FACE_VECTORIZE_ALGORITHM: ${FACE_VECTORIZE_ALGORITHM}

  api:
    restart: always
    image: ${DOCKER_REPO}/faceanalysis_app:${BUILD_TAG}
    build:
      context: ./app
      args:
        DEVTOOLS: ${DEVTOOLS}
    depends_on:
      - worker
      - mysql
      - rabbitmq
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    volumes:
      - "${DATA_DIR}:/app/faceanalysis/images"
    environment:
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      ALLOWED_IMAGE_FILE_EXTENSIONS: ${ALLOWED_IMAGE_FILE_EXTENSIONS}
      IMAGE_PROCESSOR_QUEUE: ${IMAGE_PROCESSOR_QUEUE}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      FACE_VECTORIZE_ALGORITHM: ${FACE_VECTORIZE_ALGORITHM}
      FACE_API_ACCESS_KEY: ${FACE_API_ACCESS_KEY}
      FACE_API_GROUP_ID: ${FACE_API_GROUP_ID}
      FACE_API_ENDPOINT: ${FACE_API_ENDPOINT}
      FACE_API_REGION: ${FACE_API_REGION}
      TOKEN_SECRET_KEY: ${TOKEN_SECRET_KEY}
      DEFAULT_TOKEN_EXPIRATION_SECS: ${DEFAULT_TOKEN_EXPIRATION_SECS}

  rabbitmq:
    restart: always
    image: rabbitmq:3.7.7-management
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  mysql:
    restart: always
    image: ${DOCKER_REPO}/faceanalysis_mysql:${BUILD_TAG}
    build: ./mysql
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    volumes:
      - "${DB_DIR}:/var/lib/mysql"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
