version: '3'
services:
  frontend:
    build: ./frontend
    volumes:
      - "./frontend/build:/app/build"
    env_file:
      - ./environment_variables.env
  nginx:
    restart: always
    build: ./nginx
    ports:
    - "80:80"
    volumes:
      - "./persisted_data/images:/images"
      - "./frontend/build:/frontend/build"
  image_processor:
    #restart: always
    build: ./image_processor
    volumes:
      - "./persisted_data/images:/app/image_processor/images:rw"
    env_file:
      - ./environment_variables.env
  api:
    restart: always
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - "./persisted_data/images:/app/api/images:rw"
    env_file:
      - ./environment_variables.env
  mysql:
    restart: always
    image: mysql
    volumes:
      - "./persisted_data/database:/var/lib/mysql:rw"
    env_file:
      - ./environment_variables.env
