version: '3'

services:

  nginx:
    restart: always
    image: faceanalysis_nginx:${BUILD_TAG}
    build: ./nginx
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    ports:
      - "${APP_PORT}:80"

  worker:
    restart: always
    image: faceanalysis_app:${BUILD_TAG}
    build:
      context: ./app
      args:
        DEVTOOLS: ${DEVTOOLS}
    command: ["python3", "worker.py"]
    depends_on:
      - mysql
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${DATA_DIR}:/app/faceanalysis/images"
    environment:
      HOST_DATA_DIR: "${DATA_DIR}"
      MOUNTED_DATA_DIR: /app/faceanalysis/images
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      ALLOWED_IMAGE_FILE_EXTENSIONS: ${ALLOWED_IMAGE_FILE_EXTENSIONS}
      IMAGE_PROCESSOR_QUEUE: ${IMAGE_PROCESSOR_QUEUE}
      MYSQL_CONTAINER_NAME: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DISTANCE_SCORE_THRESHOLD: ${DISTANCE_SCORE_THRESHOLD}
      FACE_VECTORIZE_ALGORITHM: ${FACE_VECTORIZE_ALGORITHM}
    env_file:
      - ./secrets.env

  api:
    restart: always
    image: faceanalysis_app:${BUILD_TAG}
    build:
      context: ./app
      args:
        DEVTOOLS: ${DEVTOOLS}
    depends_on:
      - worker
      - mysql
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    volumes:
      - "${DATA_DIR}:/app/faceanalysis/images"
    environment:
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      ALLOWED_IMAGE_FILE_EXTENSIONS: ${ALLOWED_IMAGE_FILE_EXTENSIONS}
      IMAGE_PROCESSOR_QUEUE: ${IMAGE_PROCESSOR_QUEUE}
      MYSQL_CONTAINER_NAME: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TOKEN_SECRET_KEY: ${TOKEN_SECRET_KEY}
      DEFAULT_TOKEN_EXPIRATION_SECS: ${DEFAULT_TOKEN_EXPIRATION_SECS}
    env_file:
      - ./secrets.env

  mysql:
    restart: always
    image: faceanalysis_mysql:${BUILD_TAG}
    build: ./mysql
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    volumes:
      - "${DB_DIR}:/var/lib/mysql"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
