version: '3'
services:
  nginx:
    restart: always
    build: ./nginx
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    ports:
    - "80:80"
  image_processor:
    restart: always
    build: ./image_processor
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    volumes:
      - "./persisted_data/images:/app/image_processor/images"
    env_file:
      - ./environment_variables.env
  api:
    build: ./api
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    ports:
      - "5000:5000"
    volumes:
      - "./persisted_data/images:/app/api/images"
    env_file:
      - ./environment_variables.env
  mysql:
    restart: always
    build: ./mysql
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    volumes:
      - "./persisted_data/test_database:/var/lib/mysql"
    env_file:
      - ./environment_variables.env
