version: '3'

services:

  nginx:
    restart: always
    image: faceanalysis_nginx:${BUILD_TAG}
    build: ./nginx
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    ports:
      - "${APP_PORT}:80"

  worker:
    restart: always
    image: faceanalysis_app:${BUILD_TAG}
    build:
      context: ./app
      args:
        DEVTOOLS: ${DEVTOOLS}
    command: ["python3", "worker.py"]
    depends_on:
      - mysql
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${DATA_DIR}:/app/faceanalysis/images"
    environment:
      HOST_DATA_DIR: "${DATA_DIR}"
      MOUNTED_DATA_DIR: /app/faceanalysis/images
    env_file:
      - ./environment_variables.env

  api:
    restart: always
    image: faceanalysis_app:${BUILD_TAG}
    build:
      context: ./app
      args:
        DEVTOOLS: ${DEVTOOLS}
    depends_on:
      - worker
      - mysql
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    volumes:
      - "${DATA_DIR}:/app/faceanalysis/images"
    env_file:
      - ./environment_variables.env

  mysql:
    restart: always
    image: faceanalysis_mysql:${BUILD_TAG}
    build: ./mysql
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    volumes:
      - "${DB_DIR}:/var/lib/mysql"
    env_file:
      - ./environment_variables.env
